services:
  - type: web
    name: youtube-downloader-api
    env: node
    plan: free
    buildCommand: "apt-get update && apt-get install -y python3 python3-pip && npm install && npm run build"
    startCommand: "pip install yt-dlp && node dist/server.js"
    envVars:
      - key: PORT
        value: 5000
